name: Analysis

on:
  workflow_call:

jobs:
  analysis:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle
        with:
          command: lint detektMain detektDebugUnitTest
        env:
          GoogleApiKey: ${{ secrets.PROD_GOOGLE_MAPS_API_KEY }}
      - uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          name: detektAndLint
          path: app/build/reports/**/*
          if-no-files-found: error
