name: Archive

on:
  workflow_call:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Setup signing key
        run: echo "$ChucksSigningKey" | base64 -d > $(pwd)/chuck_signing_key.jks
        env:
          ChucksSigningKey: ${{ secrets.CHUCKS_SIGNING_KEY }}
      
      - name: Build APK
        run: ./gradlew assemble --stacktrace
        env:
          GoogleApiKey: ${{ secrets.PROD_GOOGLE_MAPS_API_KEY }}
          SigningKeyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          SigningKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      
      - uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          name: apk
          path: ./**/outputs/**/*apk
          if-no-files-found: error
