name: main

on:
  push:
    branches: [main]

jobs:
  analysis:
    uses: ./.github/workflows/analysis.yml
    secrets: inherit

  archive:
    uses: ./.github/workflows/archive.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
