name: Tests

on:
  workflow_call:

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace
        env:
          GoogleApiKey: ${{ secrets.PROD_GOOGLE_MAPS_API_KEY }}
      
      - name: Upload Gradle Reports
        uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          name: gradle-reports
          path: |
            build/reports/**/*
            app/build/reports/**/*
            kmm/build/reports/**/*
          if-no-files-found: ignore
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: ${{ ! cancelled() }}
        with:
          report_paths: '**/app/build/test-results/**/*.xml'
#      - uses: actions/upload-artifact@v4
#        if: ${{ ! cancelled() }}
#        with:
#          name: testDebugUnitTest-junit-xml
#          path: |
#            app/**/reports/tests/**/*
#            app/**/test-results/**/*.xml
#          if-no-files-found: error
