name: Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle
        with:
          command: testDebugUnitTest
        env:
          GoogleApiKey: ${{ secrets.PROD_GOOGLE_MAPS_API_KEY }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: ${{ ! cancelled() }}
        with:
          report_paths: '**/app/build/test-results/**/*.xml'
      - uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          name: testDebugUnitTest-junit-xml
          path: |
            app/build/reports/tests/**/*
            app/build/test-results/**/*.xml
          if-no-files-found: error
