name: Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle
        with:
          command: testDebugUnitTest
        env:
          GoogleApiKey: ${{ secrets.PROD_GOOGLE_MAPS_API_KEY }}
